apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: test
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    repoURL: 'https://github.com/brigs/argocd-app-config'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
